version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wayni
      MYSQL_USER: wayni_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  localstack:
    image: localstack/localstack:3
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,dynamodb
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/etc/localstack/init/ready.d 
      - localstack_data:/var/lib/localstack

  ms-importer:
    build: ./ms-importer
    container_name: ms-importer
    ports:
      - "3000:3000"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PORT=3000
      - NODE_ENV=development
      - MAX_FILE_SIZE=10737418240
      - CHUNK_SIZE=65536
    depends_on:
      - localstack

  ms-api:
    build: ./ms-api
    container_name: ms-api
    ports:
      - "8000:8000"
    environment:
      - QUEUE_CONNECTION=sqs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - SQS_PREFIX=http://localstack:4566/000000000000
      - SQS_QUEUE=deudores-import-queue
      - SQS_ENDPOINT=http://localstack:4566
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  mysql_data:
  localstack_data:
